# Generated by Django 4.0.4 on 2022-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'In Progress'), ('3', 'Completed')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
