# Generated by Django 4.0.4 on 2022-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_todo_created_at_alter_todo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
