# Generated by Django 4.0.4 on 2022-05-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_todo_is_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='item',
            new_name='title',
        ),
    ]
